spring:
  redis:
    host: @virtualIp@
    port: 6379
    database: 1
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: @virtualIp@:8848
#    loadbalancer:
#      nacos:
#        enabled: true   # 开启基于nacos规则的负载均衡，如需，则在所有客户端微服务中加
    gateway:
      discovery:
        locator:
          enabled: true   # 动态路由
      # 路由配置
      routes:
        - id: userRoute
          uri: lb://user-service
          predicates:
            - Path=/u/**,/admininfo/**
        - id: companyRoute
          uri: lb://company-service
          predicates:
            - Path=/c/**
        - id: authRoute
          uri: lb://auth-service
          predicates:
            - Path=/a/**,/passport/**,/saas/**,/admin/**
        - id: resourceRoute
          uri: lb://resource-service
          predicates:
            - Path=/r/**
        - id: workRoute
          uri: lb://work-service
          predicates:
            - Path=/resume/**
        - id: fileRoute
          uri: lb://file-service
          predicates:
            - Path=/file/**
      # 网关跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true